package storagebackendcontroller

//This file is auto-generated by go-raml
//Do not edit this file by hand since it will be overwritten during the next generation

import (
	"github.com/gorilla/mux"
	"net/http"
)

// StorageclusterInterface is interface for /storagecluster root endpoint
type StorageclusterInterface interface { // GetStorageClusterInfo is the handler for GET /storagecluster/{clustername}
	// Get storage cluster information
	GetStorageClusterInfo(http.ResponseWriter, *http.Request)
}

// StorageclusterInterfaceRoutes is routing for /storagecluster root endpoint
func StorageclusterInterfaceRoutes(r *mux.Router, i StorageclusterInterface) {
	r.HandleFunc("/storagecluster/{clustername}", i.GetStorageClusterInfo).Methods("GET")
}
